### ISSUE TITLE
嵌套table中无法自定义父级的头

### ISSUE THREAD

**Issue by ld201514** [agrass-GitHub/agel-table#3]
{
          label: ‘cs’,
           slotHeader: () => {
               return <el-tag>render函数自定义列-表头</el-tag>;
           },
          children: [{ label: 'child', prop: 'name', }],
        }

**Comment by agrass-GitHub** [comment]
谢谢反馈，该组件是老早之前写的了，没怎么维护升级新功能；近期打算重构下，在下版本会修复该问题，时间可能稍微久一点。

**Comment by agrass-GitHub** [comment]
已修复
